"""
API endpoints for fetching textbook content and performing Q&A.
"""
from fastapi import APIRouter, HTTPException, Body
from pydantic import BaseModel
import logging

# Configure logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

router = APIRouter()

# --- Mock Data ---
# In a real application, this would come from a database.
mock_textbook_content = {
    "module1": {
        "title": "Introduction to Robotics",
        "content": "This is the content for Module 1. It covers the fundamental concepts of robotics, including kinematics, dynamics, and control.",
        "chapters": ["Chapter 1: History of Robotics", "Chapter 2: Robot Components"]
    },
    "module2": {
        "title": "Robot Perception",
        "content": "This is the content for Module 2. It focuses on how robots perceive the world using sensors like cameras and LiDAR.",
        "chapters": ["Chapter 3: Computer Vision", "Chapter 4: Sensor Fusion"]
    },
}

class QueryRequest(BaseModel):
    """Request model for the /query endpoint."""
    question: str
    module: str | None = None

class QueryResponse(BaseModel):
    """Response model for the /query endpoint."""
    question: str
    answer: str
    source_module: str

class ContentResponse(BaseModel):
    """Response model for the /content/{module} endpoint."""
    title: str
    content: str
    chapters: list[str]


@router.get("/content/{module}", response_model=ContentResponse)
async def get_textbook_content(module: str):
    """
    Retrieves the content for a specific textbook module.
    """
    logger.info(f"Request received for content of module: {module}")
    content = mock_textbook_content.get(module)
    if not content:
        logger.warning(f"Module '{module}' not found.")
        raise HTTPException(status_code=404, detail=f"Module '{module}' not found.")
    
    logger.info(f"Successfully retrieved content for module: {module}")
    return content

@router.post("/query", response_model=QueryResponse)
async def query_textbook(request: QueryRequest = Body(...)):
    """
    Accepts a question and returns a mock answer based on textbook content.
    """
    logger.info(f"Query received: '{request.question}' for module: {request.module or 'all'}")
    
    # This is a mock implementation.
    # A real implementation would use a RAG service or a database search.
    answer = f"This is a mock answer to your question: '{request.question}'. In a real system, this would be generated by an AI model based on the textbook content."
    source = request.module or "general"

    if request.module and request.module not in mock_textbook_content:
        raise HTTPException(status_code=404, detail=f"Module '{request.module}' not found to query against.")

    logger.info("Successfully generated mock answer.")
    return QueryResponse(
        question=request.question,
        answer=answer,
        source_module=source
    )
